import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.url(),
    AUTH_SECRET: z.string().nonempty(),
    // RAZORPAY_KEY_ID: z.string().nonempty(),
    RAZORPAY_KEY_SECRET: z.string().nonempty(),
    RAZORPAY_WEBHOOK_SECRET: z.string().min(1),
    // RESEND_API_KEY: z.string().min(1),
    CLOUDINARY_CLOUD_NAME: z.string().min(1),
    CLOUDINARY_API_KEY: z.string().min(1),
    CLOUDINARY_API_SECRET: z.string().min(1),
    WEB_PUSH_PRIVATE_KEY: z.string().min(1),
    WEB_PUSH_EMAIL: z.string().startsWith("mailto:"),
    // ADMIN_EMAIL: z.string().email(),
    // NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    // AUTH_TRUST_HOST: z.coerce.boolean().default(true),
  },
  client: {
    NEXT_PUBLIC_RAZORPAY_KEY_ID: z.string().nonempty(),
    NEXT_PUBLIC_SITE_URL: z.url(),
    NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: z.string().min(1),
    // NEXT_PUBLIC_SITE_NAME: z.string(),
    // NEXT_PUBLIC_EMAIL_ENGINE_MAIL: z.string().email(),
    // NEXT_PUBLIC_ADMIN_EMAIL: z.string().email(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    RAZORPAY_WEBHOOK_SECRET: process.env.RAZORPAY_WEBHOOK_SECRET,
    NEXT_PUBLIC_RAZORPAY_KEY_ID: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
    // RAZORPAY_WEBHOOK_SECRET: process.env.RAZORPAY_WEBHOOK_SECRET,
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
    WEB_PUSH_PRIVATE_KEY: process.env.WEB_PUSH_PRIVATE_KEY,
    WEB_PUSH_EMAIL: process.env.WEB_PUSH_EMAIL,
    NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: process.env.NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY,
    // RESEND_API_KEY: process.env.RESEND_API_KEY,
    // ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    // NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    // AUTH_TRUST_HOST: process.env.AUTH_TRUST_HOST,
    // NEXT_PUBLIC_SITE_NAME: process.env.NEXT_PUBLIC_SITE_NAME,
    // NEXT_PUBLIC_EMAIL_ENGINE_MAIL: process.env.NEXT_PUBLIC_EMAIL_ENGINE_MAIL,
    // NEXT_PUBLIC_ADMIN_EMAIL: process.env.NEXT_PUBLIC_ADMIN_EMAIL,
  },
});
